/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : IV2.h
**     Project     : ProcessorExpert
**     Processor   : MCF51QE128CLH
**     Component   : InterruptVector
**     Version     : Component 02.023, Driver 01.08, CPU db: 3.00.080
**     Compiler    : CodeWarrior ColdFireV1 C Compiler
**     Date/Time   : 2013-04-22, 15:48, # CodeGen: 52
**     Abstract    :
**         This component "InterruptVector" gives an access to interrupt vector.
**         The purpose of this component is to allocate the interrupt vector
**         in the vector table. Additionally it can provide settings of
**         the interrupt priority register.
**         The interrupt handling routines must be implemented by the user.
**     Settings    :
**         Interrupt vector            : Vtrap14
**         Handle name                 : OSSyscallISR
**     Contents    :
**         No public methods
**
**     Copyright : 1997 - 2012 Freescale, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __IV2
#define __IV2

/* MODULE IV2. */

#include "PE_Types.h"

/*
** ===================================================================
** The interrupt service routine must be implemented by user in one
** of the user modules (see IV2.c file for more information).
** ===================================================================
*/
__interrupt void OSSyscallISR(void);

/* END IV2. */

#endif /* ifndef __IV2 */
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.0 [05.03]
**     for the Freescale ColdFireV1 series of microcontrollers.
**
** ###################################################################
*/
